### PR TITLE
Refactor sip method and some bug fixes

### PR DESCRIPTION
**Pull request by rlsutton1**
This pull request refactors the Sip Method from a String to an Enum and infers types where possible which should ease the long term maintenance of the project.

Included are a few bug fixes, namely 
* the use of Slice() is SIPMessage.dart
* fix for Exception in Parser.dart

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
LGTM

**Comment by cloudwebrtc** [comment]
Using a strong type instead of a var variable declaration is a very good idea, and later will gradually replace the var declaration with a real type.

**Comment by rlsutton1** [comment]
I've removed error, It should compile cleanly now

**Comment by cloudwebrtc** [comment]
@rlsutton1 I have merged the PR and regenerated the grammar parser.
on
```dart
//TODO: Commented out because this seems to cause errors with Asterisk

//await this._connection.setRemoteDescription(answer);
```
I temporarily removed the comments, I think the process here should be no problem, the error should be caused by other reasons.

You can provide some device logs about asterisk calls to help locate the problem.

**Comment by rlsutton1** [comment]
> @rlsutton1 I have merged the PR and regenerated the grammar parser.
> on
> 
> ```dart
> //TODO: Commented out because this seems to cause errors with Asterisk
> 
> //await this._connection.setRemoteDescription(answer);
> ```
> 
> I temporarily removed the comments, I think the process here should be no problem, the error should be caused by other reasons.
> 
> You can provide some device logs about asterisk calls to help locate the problem.

OK, I'll try to provide some logs tomorrow.

**Pull request merged**
